### PR TITLE
Update schema for label backgrounds.

### PR DESCRIPTION
**Pull request by emackey**
For AnalyticalGraphicsInc/cesium#4715.

**TODO**

- [x] Regenerate code

### CODE REVIEW

**Comment by pjcozzi** [comment]
@shunter do you want to review?

**Comment by emackey** [comment]
This is ready.

**Comment by emackey** [comment]
This is NOT ready.  I'm getting

> The type or namespace `BackgroundPaddingCesiumWriter` could not be found.

**Comment by emackey** [comment]
Fixed.  This is ready again.

**Comment by shunter** [comment]
I used this branch to add the other CZML properties that were put into Cesium but not added to the writer.  Merging.

**Pull request merged**
